site_name: 语音与语言处理

nav:
  - 主页:
    - "index.md"
  - 最新论文:
    - "paper/本周值得读_2022_04_23.md"
  - 信号处理:
    - "dsp/参考资料.md"
    - "dsp/语音基本概念.md"
    - "dsp/语音特征提取.md"
  - 语音合成:
    - "tts/语音合成概述.md"
    - "tts/语音合成的评价标准和方法.md"
    - "tts/语言学.md"
    - "tts/音库制作和文本前端.md"
    - "tts/声学模型.md"
    - "tts/声码器.md"
    - "tts/语音合成的总体知识体系.md"
  - 语音识别:
    - "asr/wenet总体解析.md"
    - "asr/wenet_runtime知识点.md"
    - "asr/wenet_kaitang-ssl-train知识点.md"
    - "asr/加权有限状态机.md"
    - "asr/arpa2fst将语言模型转为WFST.md"
    - "asr/kaldi中的解码过程.md"
    - "asr/kaldi中的Simple-Decoder.md"
    - "asr/OpenFST基本操作.md"
    - "asr/wenet的ctc_alignment.md"
    - "asr/wenet的ctc_prefix_beam_search.md"
    - "asr/wenet对onnx的支持.md"
    - "asr/wenet中endpoint检测.md"
  - 开源数据和工具:
    - 主页: "open_source_index.md"
  - 开发:
    - docker:
      - "develop/docker/docker常用命令.md"
    - python:
      - "develop/python/python的取反运算符.md"
      - "develop/python/正则表达式.md"
      - "develop/python/conda和pip.md"
      - "develop/python/numpy存取数据.md"
      - "develop/python/__future__用法.md"
    - shell:
      - "develop/shell/Linux操作基础备忘录.md"
      - "develop/shell/vim.md"
      - "develop/shell/top_linux下的任务管理器.md"
      - "develop/shell/shell调试.md"
      - "develop/shell/cat和EOF.md"
      - "develop/shell/tailf.md"
      - "develop/shell/shell语法速查手册.md"
    - cpp:
      - "develop/cpp/stl的map.md"
      - "develop/cpp/cpp调试.md"
      - "develop/cpp/cpp的类访问修饰符.md"
      - "develop/cpp/cpp关键字const修饰函数.md"
      - "develop/cpp/cpp宽字符wchar.md"
      - "develop/cpp/gcc的常用编译选项.md"
      - "develop/cpp/c或cpp软件编译.md"
      - "develop/cpp/stl的vector.md"
      - "develop/cpp/cpp中的int_t.md"
      - "develop/cpp/stl的string.md"
      - "develop/cpp/cpp右值引用.md"
      - "develop/cpp/cpp并发编程.md"
      - "develop/cpp/c及cpp的文件读写.md"
      - "develop/cpp/cpp常用库gflags_glog_gtest.md"
    - git:
      - "develop/git/git中的HEAD.md"
      - "develop/git/git常用回退操作.md"
      - "develop/git/git的指针ref和reflog.md"
      - "develop/git/git转移部分代码cherry-pick.md"
      - "develop/git/git日志.md"
      - "develop/git/git分支合并.md"
      - "develop/git/git的fast_forward.md"
      - "develop/git/git修改提交信息.md"
      - "develop/git/git学习资源.md"
  - 数据结构:
    - "leetcode/滑动窗口专题.md"
    - "leetcode/DFS回溯算法专题.md"
    - "leetcode/一般二叉树专题.md"
    - "leetcode/二叉搜索树专题.md"
  
# reference: https://squidfunk.github.io/mkdocs-material/reference/
theme:
  name: material
  language: zh
  features:
    # reference: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - toc.follow
    - toc.integrate
    - navigation.top
    # reference: https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search
    - search.suggest
    - search.highlight
    - search.share
  icon:
    repo: fontawesome/brands/git-alt
  # reference: https://squidfunk.github.io/mkdocs-material/setup/adding-a-comment-system
  custom_dir: overrides

# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository
repo_url: https://github.com/cnlinxi/blog
repo_name: cnlinxi/blog
edit_uri: edit/main/docs/

plugins:
  - search:
      separator: '[\s\-\.]'
  - git-revision-date

# reference: https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.keys
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.smartsymbols
  - pymdownx.arithmatex:
      generic: true
  - tables

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
